name: CI-CD
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
      - name: Setup Nodejs 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build