name: CI-CD
on: [push]
env:
  prod-dist: 'product-distribution'
  stream_name: ${{ secrets.STREAM_NAME }} 
  publishing_token: ${{ secrets.STREAM_PUBLISHING_TOKEN }}
  account_id: ${{secrets.STREAM_ACCOUNT_ID }}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
      - name: Setup Nodejs 16.x then Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: |
          yarn --frozen-lockfile
          yarn prebuild
          yarn build

  # TODO: test job for pull request