name: CI-CD
on: [push]
env:
  prod-dist: 'product-distribution'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3

      - name: Setup Nodejs 16.x then Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: |
          yarn --frozen-lockfile
          yarn build

      - name: Upload production artifacts
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        with:
          name: ${{ env.prod-dist }}
          retention-days: 1
          if-no-files-found: error
          path: |
            dist

  # TODO: test job for pull request

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.prod-dist }}
      # TODO  
      # - name: deploy to Netlify